site_name: SysPoe's Train Wiki
theme: readthedocs
# site_url: https://syspoe.github.io/train-wiki/
site_author: SysPoe
# site_description: ""
repo_url: https://github.com/SysPoe/train-wiki/
edit_uri: edit/main/docs/
# copyright: ""
nav:
  - index.md
  - Rollingstock:
      # - Rollingstock/index.md
      - Rollingstock/ICE.md
      - Rollingstock/EMU.md
      - Rollingstock/IMU.md
      - Rollingstock/SMU.md
      - Rollingstock/NGR.md
      - Rollingstock/QTMP.md
  - Train Spotting:
      # - Train-Spotting/index.md
      - Train-Spotting/AnyTrip.md
      - Train-Spotting/Best-Lines.md
      - Train-Spotting/Cool-Rides.md
      - Good Trainspotting Locations:
          - Train-Spotting/Good-Trainspotting-Locations/Eagle-Junction.md
          - Train-Spotting/Good-Trainspotting-Locations/Petrie.md
      - Train-Spotting/Radio-Frequencies.md
      - Train-Spotting/Run-Numbering-Guide.md
      - Train-Spotting/Tips-While-Lineside.md
  - Gallery:
      - Gallery/Blueprints.md
      - Gallery/Cool-Maps.md
      - Gallery/Dark-Trains.md
      - Gallery/My-Photos.md
  - Other:
      - Other/Brisbane-Day-Trips.md
      - Other/Glossary.md
      - Other/Honk.md
      - Other/SEQ-Craziness.md
      - Other/Station-Abbreviations.md
      - Other/Resources.md
      - List of Resources:
        - Other/Resources/Freight-Sightings.md
        - FTT/index.md
        - PID Maker: Other/Resources/PID/index.html
        - Other/Resources/RunGuru/index.md

markdown_extensions:
  - toc:
      permalink: true

validation:
  omitted_files: warn
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
